CREATE TABLE [Search].[Provider] (
    [ProviderId]          INT            NOT NULL,
    [ProviderName]        NVARCHAR (200) NOT NULL,
    [Ukprn]               INT            NOT NULL,
    [ProviderTypeId]      INT            NOT NULL,
    [Email]               NVARCHAR (255) NULL,
    [Website]             NVARCHAR (511) NULL,
    [Telephone]           NVARCHAR (30)  NULL,
    [Fax]                 NVARCHAR (30)  NULL,
    [TradingName]         NVARCHAR (255) NULL,
    [LegalName]           NVARCHAR (255) NOT NULL,
    [UPIN]                INT            NULL,
    [ProviderNameAlias]   NVARCHAR (200) NULL,
    [CreatedDateTimeUtc]  DATETIME       NOT NULL,
    [ModifiedDateTimeUtc] DATETIME       NULL,
    [Loans24Plus]         BIT            NOT NULL,
    [RecordStatusId]      INT            NOT NULL,
    [CreatedByUserId]     NVARCHAR (128) NOT NULL,
    [ModifiedByUserId]    NVARCHAR (128) NULL,
    [AddressLine1]        NVARCHAR (100) NOT NULL,
    [AddressLine2]        NVARCHAR (100) NULL,
    [Town]                NVARCHAR (75)  NOT NULL,
    [County]              NVARCHAR (75)  NULL,
    [Postcode]            NVARCHAR (30)  NOT NULL,
    [ApplicationId]       INT            NOT NULL,
    [DFE1619Funded]		  BIT			 NOT NULL DEFAULT 0, 
    [FEChoices_LearnerDestination] FLOAT NULL, 
    [FEChoices_LearnerSatisfaction] FLOAT NULL, 
    [FEChoices_EmployerSatisfaction] FLOAT NULL, 
    [SFAFunded] BIT NOT NULL DEFAULT 0, 
    PRIMARY KEY NONCLUSTERED ([ProviderId] ASC)
);

