CREATE TABLE [Search].[Venue] (
    [VenueId]             INT             NOT NULL,
	[ProviderId]          INT             NOT NULL,
    [VenueName]           NVARCHAR (255)  NOT NULL,
    [ProviderOwnVenueRef] NVARCHAR (255)  NULL,
    [Telephone]           NVARCHAR (30)   NULL,
    [AddressLine1]        NVARCHAR (100)  NOT NULL,
    [AddressLine2]        NVARCHAR (100)  NULL,
    [Town]                NVARCHAR (75)   NOT NULL,
    [County]              NVARCHAR (75)   NULL,
    [Postcode]            NVARCHAR (30)   NOT NULL,
    [Email]               NVARCHAR (255)  NULL,
    [Website]             NVARCHAR (511)  NULL,
    [Fax]                 NVARCHAR (35)   NULL,
    [Facilities]          NVARCHAR (2000) NULL,
    [CreatedDateTimeUtc]  DATETIME        NOT NULL,
    [ModifiedDateTimeUtc] DATETIME        NULL,
    [RecordStatusId]      INT             NOT NULL,
    [CreatedByUserId]     NVARCHAR (128)  NOT NULL,
    [ModifiedByUserId]    NVARCHAR (128)  NULL,
    [Easting]             FLOAT (53)      NULL,
    [Northing]            FLOAT (53)      NULL,
    [SearchRegion]        NVARCHAR (30)   NOT NULL,
    [ApplicationId]       INT             NOT NULL, 
    [Latitude]			  FLOAT NULL, 
    [Longitude]		      FLOAT NULL, 
	[Geography] as geography::STGeomFromText('Point(' + CAST([Longitude] AS VARCHAR(32)) + ' ' + CAST([Latitude] AS VARCHAR(32)) + ')',4326),
	-- Address Base
	[PostTown]			  NVARCHAR(30)	  NULL,
	[DependentLocality]   NVARCHAR(35)	  NULL,
	[DoubleDependentLocality]   NVARCHAR(35)	NULL,
	-- Venue Location Hierarchy
	[VenueLocationId]			INT				NULL,
	-- ONS_PostcodeDirectory
	[EuropeanElectoralRegion]	NVARCHAR(24)	NULL,
    [LocalAuthorityDistrict]	NVARCHAR(36)	NULL,
    [CurrentElectoralWard]		NVARCHAR(56)	NULL,
    [OnsCounty]					NVARCHAR(27)	NULL,
	[CountyAliasId]				INT				NULL,
	[ParishCommunity]			NVARCHAR(70)	NULL,
    [CensusBuiltUpAreaSubDivision]	NVARCHAR(47)	NULL,
    [RegionLevelPenalty] FLOAT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_Venue] PRIMARY KEY ([VenueId])
);

