//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.NCS.CourseSearchService.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopWord
    {
        public int StopWordId { get; set; }
        public string StopWordName { get; set; }
    }
}
