CREATE PROCEDURE [remote].[CopyOverCourseInstance]
AS
BEGIN

	TRUNCATE TABLE [search].[CourseInstance];
	INSERT INTO [search].[CourseInstance] (
		[CourseInstanceId]
		, [ProviderOwnCourseInstanceRef]
		, [Price]
		, [PriceAsText]
		, [DurationUnitId]
		, [DurationUnitBulkUploadRef]
		, [DurationUnitName]
		, [DurationAsText]
		, [StartDateDescription]
		, [EndDate]
		, [StudyModeBulkUploadRef]
		, [StudyModeName]
		, [AttendanceModeBulkUploadRef]
		, [AttendanceModeName]
		, [AttendancePatternBulkUploadRef]
		, [AttendancePatternName]
		, [LanguageOfInstruction]
		, [LanguageOfAssessment]
		, [PlacesAvailable]
		, [EnquiryTo]
		, [ApplyTo]
		, [ApplyFromDate]
		, [ApplyUntilDate]
		, [ApplyUntilText]
		, [Url]
		, [TimeTable]
		, [CourseId]
		, [VenueId]
		, [CanApplyAllYear]
		, [RegionName]
		, [CreatedDateTimeUtc]
		, [ModifiedDateTimeUtc]
		, [RecordStatusId]
		, [CreatedByUserId]
		, [ModifiedByUserId]
		, [CourseInstanceSummary]
		, [ProviderRegionId]
		, [ApplicationId]
		, [OfferedByOrganisationId]
		, [OfferedByProviderId]
		, [StartDate]
		, [A10Codes]
		, [DfEFunded]
		, [VenueLocationId]
	)
	SELECT
		[CourseInstanceId]
		, [ProviderOwnCourseInstanceRef]
		, [Price]
		, [PriceAsText]
		, [DurationUnitId]
		, [DurationUnitBulkUploadRef]
		, [DurationUnitName]
		, [DurationAsText]
		, [StartDateDescription]
		, [EndDate]
		, [StudyModeBulkUploadRef]
		, [StudyModeName]
		, [AttendanceModeBulkUploadRef]
		, [AttendanceModeName]
		, [AttendancePatternBulkUploadRef]
		, [AttendancePatternName]
		, [LanguageOfInstruction]
		, [LanguageOfAssessment]
		, [PlacesAvailable]
		, [EnquiryTo]
		, [ApplyTo]
		, [ApplyFromDate]
		, [ApplyUntilDate]
		, [ApplyUntilText]
		, [Url]
		, [TimeTable]
		, [CourseId]
		, [VenueId]
		, [CanApplyAllYear]
		, [RegionName]
		, [CreatedDateTimeUtc]
		, [ModifiedDateTimeUtc]
		, [RecordStatusId]
		, [CreatedByUserId]
		, [ModifiedByUserId]
		, [CourseInstanceSummary]
		, [ProviderRegionId]
		, [ApplicationId]
		, [OfferedByOrganisationId]
		, [OfferedByProviderId]
		, [StartDate]
		, [A10Codes]
		, [DfEFunded]
		, [VenueLocationId]
	FROM [remote].[CourseInstance];
	  
	RETURN 0;

END;