CREATE PROCEDURE [remote].[CopyOverCourse]
AS
BEGIN

TRUNCATE TABLE [search].[Course]
INSERT INTO [search].[Course] (
	[CourseId]
	,  [ProviderId]
	,  [LearningAimRef]
	,  [CourseTitle]
	,  [CourseSummary]
	,  [ProviderOwnCourseRef]
	,  [Url]
	,  [BookingUrl]
	,  [EntryRequirements]
	,  [AssessmentMethod]
	,  [EquipmentRequired]
	,  [QualificationTitle]
	,  [QualificationBulkUploadRef]
	,  [QualificationLevelName]
	,  [LDCS1]
	,  [LDCS2]
	,  [LDCS3]
	,  [LDCS4]
	,  [LDCS5]
	,  [ApplicationId]
	,  [UcasTariffPoints]
	,  [QualificationRefAuthority]
	,  [QualificationRef]
	,  [CourseTypeId]
	,  [CreatedDateTimeUtc]
	,  [ModifiedDateTimeUtc]
	,  [RecordStatusId]
	,  [AwardingOrganisationName]
	,  [CreatedByUserId]
	,  [ModifiedByUserId]
	,  [QualificationTypeRef]
	,  [QualificationTypeName]
	,  [QualificationDataType]
	,  [PrimaryApplicationId]
	,  [ErAppStatus]               
	,  [SkillsForLife]             
	,  [Loans24Plus]               
	,  [AdultLearnerFundingStatus] 
	,  [OtherFundingStatus]        
	,  [IndependentLivingSkills]   
)
SELECT
	[CourseId]
	,  [ProviderId]
	,  [LearningAimRef]
	,  [CourseTitle]
	,  [CourseSummary]
	,  [ProviderOwnCourseRef]
	,  [Url]
	,  [BookingUrl]
	,  [EntryRequirements]
	,  [AssessmentMethod]
	,  [EquipmentRequired]
	,  [QualificationTitle]
	,  [QualificationBulkUploadRef]
	,  [QualificationLevelName]
	,  [LDCS1]
	,  [LDCS2]
	,  [LDCS3]
	,  [LDCS4]
	,  [LDCS5]
	,  [ApplicationId]
	,  [UcasTariffPoints]
	,  [QualificationRefAuthority]
	,  [QualificationRef]
	,  [CourseTypeId]
	,  [CreatedDateTimeUtc]
	,  [ModifiedDateTimeUtc]
	,  [RecordStatusId]
	,  [AwardingOrganisationName]
	,  [CreatedByUserId]
	,  [ModifiedByUserId]
	,  [QualificationTypeRef]
	,  [QualificationTypeName]
	,  [QualificationDataType]
	,  [PrimaryApplicationId]
	,  [ErAppStatus]               
	,  [SkillsForLife]             
	,  [Loans24Plus]               
	,  [AdultLearnerFundingStatus] 
	,  [OtherFundingStatus]        
	,  [IndependentLivingSkills]   
FROM [remote].[Course]

RETURN 0
END