CREATE PROCEDURE [remote].[CopyOverVenue]
AS
BEGIN

	TRUNCATE TABLE [search].[Venue];
	INSERT INTO [search].[Venue] (
		[ProviderId]
		, [VenueId]
		, [VenueName]
		, [ProviderOwnVenueRef]
		, [Telephone]
		, [AddressLine1]
		, [AddressLine2]
		, [Town]
		, [County]
		, [Postcode]
		, [Email]
		, [Website]
		, [Fax]
		, [Facilities]
		, [CreatedDateTimeUtc]
		, [ModifiedDateTimeUtc]
		, [RecordStatusId]
		, [CreatedByUserId]
		, [ModifiedByUserId]
		, [Easting]
		, [Northing]
		, [SearchRegion]
		, [ApplicationId]
		, [Latitude]
		, [Longitude]
		, [Geography]
		, [PostTown]
		, [DependentLocality]
		, [DoubleDependentLocality]
		, [VenueLocationId]
		, [EuropeanElectoralRegion]
		, [LocalAuthorityDistrict]
		, [CurrentElectoralWard]
		, [OnsCounty]
		, [CountyAliasId]
		, [ParishCommunity]
		, [CensusBuiltUpAreaSubDivision]
		, [RegionLevelPenalty]
	)
	SELECT
		[ProviderId]
		, [VenueId]
		, [VenueName]
		, [ProviderOwnVenueRef]
		, [Telephone]
		, [AddressLine1]
		, [AddressLine2]
		, [Town]
		, [County]
		, [Postcode]
		, [Email]
		, [Website]
		, [Fax]
		, [Facilities]
		, [CreatedDateTimeUtc]
		, [ModifiedDateTimeUtc]
		, [RecordStatusId]
		, [CreatedByUserId]
		, [ModifiedByUserId]
		, [Easting]
		, [Northing]
		, [SearchRegion]
		, [ApplicationId]
		, [Latitude]
		, [Longitude]
		, [Geography]
		, [PostTown]
		, [DependentLocality]
		, [DoubleDependentLocality]
		, [VenueLocationId]
		, [EuropeanElectoralRegion]
		, [LocalAuthorityDistrict]
		, [CurrentElectoralWard]
		, [OnsCounty]
		, [CountyAliasId]
		, [ParishCommunity]
		, [CensusBuiltUpAreaSubDivision]
		, [RegionLevelPenalty]
	FROM [remote].[Venue];
	  
	RETURN 0;

END;