CREATE PROCEDURE [remote].[CopyOverProvider]
AS
BEGIN

TRUNCATE TABLE [search].[Provider]
INSERT INTO [search].[Provider] (
	[ProviderId]
	,  [ProviderName]
	,  [Ukprn]
	,  [ProviderTypeId]
	,  [Email]
	,  [Website]
	,  [Telephone]
	,  [Fax]
	,  [TradingName]
	,  [LegalName]
	,  [UPIN]
	,  [ProviderNameAlias]
	,  [CreatedDateTimeUtc]
	,  [ModifiedDateTimeUtc]
	,  [Loans24Plus]
	,  [RecordStatusId]
	,  [CreatedByUserId]
	,  [ModifiedByUserId]
	,  [AddressLine1]
	,  [AddressLine2]
	,  [Town]
	,  [County]
	,  [Postcode]
	,  [ApplicationId]
	,  [DFE1619Funded]
	,  [SFAFunded]
	,  [FEChoices_LearnerDestination]
	,  [FEChoices_LearnerSatisfaction]
	,  [FEChoices_EmployerSatisfaction]
)
SELECT
	[ProviderId]
	,  [ProviderName]
	,  [Ukprn]
	,  [ProviderTypeId]
	,  [Email]
	,  [Website]
	,  [Telephone]
	,  [Fax]
	,  [TradingName]
	,  [LegalName]
	,  [UPIN]
	,  [ProviderNameAlias]
	,  [CreatedDateTimeUtc]
	,  [ModifiedDateTimeUtc]
	,  [Loans24Plus]
	,  [RecordStatusId]
	,  [CreatedByUserId]
	,  [ModifiedByUserId]
	,  [AddressLine1]
	,  [AddressLine2]
	,  [Town]
	,  [County]
	,  [Postcode]
	,  [ApplicationId]
	,  [DFE1619Funded]
	,  [SFAFunded]
	,  [FEChoices_LearnerDestination]
	,  [FEChoices_LearnerSatisfaction]
	,  [FEChoices_EmployerSatisfaction]
FROM [remote].[Provider]
	  
RETURN 0
END