//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class A10FundingCode
    {
        public A10FundingCode()
        {
            this.CourseInstances = new HashSet<CourseInstance>();
        }
    
        public int A10FundingCodeId { get; set; }
        public string A10FundingCodeName { get; set; }
        public int RecordStatusId { get; set; }
    
        public virtual RecordStatu RecordStatu { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
    }
}
