//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Ukrlps = new HashSet<Ukrlp>();
            this.Ukrlps1 = new HashSet<Ukrlp>();
            this.Providers = new HashSet<Provider>();
            this.Venues = new HashSet<Venue>();
            this.Organisations = new HashSet<Organisation>();
            this.Locations = new HashSet<Location>();
        }
    
        public int AddressId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public Nullable<int> ProviderRegionId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geography { get; set; }
    
        public virtual ProviderRegion ProviderRegion { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<Ukrlp> Ukrlps { get; set; }
        public virtual ICollection<Ukrlp> Ukrlps1 { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
        public virtual ICollection<Venue> Venues { get; set; }
        public virtual ICollection<Organisation> Organisations { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
