//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressBase
    {
        public decimal UPRN { get; set; }
        public string Postcode { get; set; }
        public string OrganisationName { get; set; }
        public string DepartmentName { get; set; }
        public string POBoxNumber { get; set; }
        public string BuildingName { get; set; }
        public string SubBuildingName { get; set; }
        public Nullable<int> BuildingNumber { get; set; }
        public string DependentThoroughfareName { get; set; }
        public string ThoroughfareName { get; set; }
        public string Town { get; set; }
        public string DoubleDependentLocality { get; set; }
        public string DependentLocality { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    }
}
