//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Courses = new HashSet<Course>();
            this.CourseInstances = new HashSet<CourseInstance>();
            this.QualityScores = new HashSet<QualityScore>();
            this.ApprenticeshipLocations = new HashSet<ApprenticeshipLocation>();
            this.Apprenticeships = new HashSet<Apprenticeship>();
        }
    
        public int ApplicationId { get; set; }
        public string ApplicationName { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
        public virtual ICollection<QualityScore> QualityScores { get; set; }
        public virtual ICollection<ApprenticeshipLocation> ApprenticeshipLocations { get; set; }
        public virtual ICollection<Apprenticeship> Apprenticeships { get; set; }
    }
}
