//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprenticeshipLocation
    {
        public ApprenticeshipLocation()
        {
            this.DeliveryModes = new HashSet<DeliveryMode>();
        }
    
        public int ApprenticeshipLocationId { get; set; }
        public int ApprenticeshipId { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> Radius { get; set; }
        public int RecordStatusId { get; set; }
        public int AddedByApplicationId { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
    
        public virtual Apprenticeship Apprenticeship { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<DeliveryMode> DeliveryModes { get; set; }
        public virtual Application Application { get; set; }
        public virtual RecordStatu RecordStatu { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
