//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apprenticeship
    {
        public Apprenticeship()
        {
            this.ApprenticeshipLocations = new HashSet<ApprenticeshipLocation>();
            this.ApprenticeshipQACompliances = new HashSet<ApprenticeshipQACompliance>();
            this.ApprenticeshipQAStyles = new HashSet<ApprenticeshipQAStyle>();
        }
    
        public int ApprenticeshipId { get; set; }
        public int ProviderId { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
        public int AddedByApplicationId { get; set; }
        public int RecordStatusId { get; set; }
        public Nullable<int> StandardCode { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> FrameworkCode { get; set; }
        public Nullable<int> ProgType { get; set; }
        public Nullable<int> PathwayCode { get; set; }
        public string MarketingInformation { get; set; }
        public string Url { get; set; }
        public string ContactTelephone { get; set; }
        public string ContactEmail { get; set; }
        public string ContactWebsite { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual RecordStatu RecordStatu { get; set; }
        public virtual Standard Standard { get; set; }
        public virtual ICollection<ApprenticeshipLocation> ApprenticeshipLocations { get; set; }
        public virtual Framework Framework { get; set; }
        public virtual Application Application { get; set; }
        public virtual ICollection<ApprenticeshipQACompliance> ApprenticeshipQACompliances { get; set; }
        public virtual ICollection<ApprenticeshipQAStyle> ApprenticeshipQAStyles { get; set; }
    }
}
