//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRole
    {
        public AspNetRole()
        {
            this.ProviderUserTypeInRoles = new HashSet<ProviderUserTypeInRole>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LanguageFieldName { get; set; }
        public int UserContextId { get; set; }
    
        public virtual ICollection<ProviderUserTypeInRole> ProviderUserTypeInRoles { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
