//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Courses = new HashSet<Course>();
            this.Courses1 = new HashSet<Course>();
            this.Providers = new HashSet<Provider>();
            this.Providers1 = new HashSet<Provider>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.Providers2 = new HashSet<Provider>();
            this.Organisations = new HashSet<Organisation>();
            this.Organisations1 = new HashSet<Organisation>();
            this.Organisations2 = new HashSet<Organisation>();
            this.BulkUploadStatusHistories = new HashSet<BulkUploadStatusHistory>();
            this.Contents = new HashSet<Content>();
            this.Contents1 = new HashSet<Content>();
            this.QualityScores = new HashSet<QualityScore>();
            this.QualityScores1 = new HashSet<QualityScore>();
            this.MetadataUploads = new HashSet<MetadataUpload>();
            this.UserProvisionHistories = new HashSet<UserProvisionHistory>();
            this.Apprenticeships = new HashSet<Apprenticeship>();
            this.Apprenticeships1 = new HashSet<Apprenticeship>();
            this.ApprenticeshipLocations = new HashSet<ApprenticeshipLocation>();
            this.ApprenticeshipLocations1 = new HashSet<ApprenticeshipLocation>();
            this.AspNetUsers1 = new HashSet<AspNetUser>();
            this.AspNetUsers11 = new HashSet<AspNetUser>();
            this.CourseInstances = new HashSet<CourseInstance>();
            this.CourseInstances1 = new HashSet<CourseInstance>();
            this.Locations = new HashSet<Location>();
            this.Locations1 = new HashSet<Location>();
            this.Organisations3 = new HashSet<Organisation>();
            this.Organisations21 = new HashSet<Organisation>();
            this.Providers3 = new HashSet<Provider>();
            this.Providers21 = new HashSet<Provider>();
            this.Venues = new HashSet<Venue>();
            this.Venues1 = new HashSet<Venue>();
            this.ApprenticeshipQACompliances = new HashSet<ApprenticeshipQACompliance>();
            this.ApprenticeshipQAStyles = new HashSet<ApprenticeshipQAStyle>();
            this.ProviderQACompliances = new HashSet<ProviderQACompliance>();
            this.ProviderQAStyles = new HashSet<ProviderQAStyle>();
            this.Provider_AllCoursesOKConfirmations = new HashSet<Provider_AllCoursesOKConfirmations>();
            this.ProviderUnableToCompletes = new HashSet<ProviderUnableToComplete>();
            this.ImportBatchProviders = new HashSet<ImportBatchProvider>();
            this.Providers22 = new HashSet<Provider>();
            this.SearchPhrases = new HashSet<SearchPhrase>();
            this.SearchPhrases1 = new HashSet<SearchPhrase>();
            this.ProviderTASRefreshes = new HashSet<ProviderTASRefresh>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public Nullable<int> AddressId { get; set; }
        public bool PasswordResetRequired { get; set; }
        public int ProviderUserTypeId { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
        public bool IsDeleted { get; set; }
        public int LegacyUserId { get; set; }
        public Nullable<System.DateTime> LastLoginDateTimeUtc { get; set; }
        public bool IsSecureAccessUser { get; set; }
        public Nullable<int> SecureAccessUserId { get; set; }
        public Nullable<bool> ShowUserWizard { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ProviderUserType ProviderUserType { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Course> Courses1 { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
        public virtual ICollection<Provider> Providers1 { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<Provider> Providers2 { get; set; }
        public virtual ICollection<Organisation> Organisations { get; set; }
        public virtual ICollection<Organisation> Organisations1 { get; set; }
        public virtual ICollection<Organisation> Organisations2 { get; set; }
        public virtual ICollection<BulkUploadStatusHistory> BulkUploadStatusHistories { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<Content> Contents1 { get; set; }
        public virtual ICollection<QualityScore> QualityScores { get; set; }
        public virtual ICollection<QualityScore> QualityScores1 { get; set; }
        public virtual ICollection<MetadataUpload> MetadataUploads { get; set; }
        public virtual ICollection<UserProvisionHistory> UserProvisionHistories { get; set; }
        public virtual ICollection<Apprenticeship> Apprenticeships { get; set; }
        public virtual ICollection<Apprenticeship> Apprenticeships1 { get; set; }
        public virtual ICollection<ApprenticeshipLocation> ApprenticeshipLocations { get; set; }
        public virtual ICollection<ApprenticeshipLocation> ApprenticeshipLocations1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers11 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances1 { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Location> Locations1 { get; set; }
        public virtual ICollection<Organisation> Organisations3 { get; set; }
        public virtual ICollection<Organisation> Organisations21 { get; set; }
        public virtual ICollection<Provider> Providers3 { get; set; }
        public virtual ICollection<Provider> Providers21 { get; set; }
        public virtual ICollection<Venue> Venues { get; set; }
        public virtual ICollection<Venue> Venues1 { get; set; }
        public virtual ICollection<ApprenticeshipQACompliance> ApprenticeshipQACompliances { get; set; }
        public virtual ICollection<ApprenticeshipQAStyle> ApprenticeshipQAStyles { get; set; }
        public virtual ICollection<ProviderQACompliance> ProviderQACompliances { get; set; }
        public virtual ICollection<ProviderQAStyle> ProviderQAStyles { get; set; }
        public virtual ICollection<Provider_AllCoursesOKConfirmations> Provider_AllCoursesOKConfirmations { get; set; }
        public virtual ICollection<ProviderUnableToComplete> ProviderUnableToCompletes { get; set; }
        public virtual ICollection<ImportBatchProvider> ImportBatchProviders { get; set; }
        public virtual ICollection<Provider> Providers22 { get; set; }
        public virtual ICollection<SearchPhrase> SearchPhrases { get; set; }
        public virtual ICollection<SearchPhrase> SearchPhrases1 { get; set; }
        public virtual ICollection<ProviderTASRefresh> ProviderTASRefreshes { get; set; }
    }
}
