//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkUploadExceptionItem
    {
        public int BulkUploadExceptionItemId { get; set; }
        public int BulkUploadId { get; set; }
        public int BulkUploadSectionId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public int BulkUploadErrorTypeId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string ColumnName { get; set; }
        public string ColumnValue { get; set; }
        public string Details { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
    
        public virtual BulkUpload BulkUpload { get; set; }
        public virtual BulkUploadErrorType BulkUploadErrorType { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
