//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkUploadStatu
    {
        public BulkUploadStatu()
        {
            this.BulkUploadStatusHistories = new HashSet<BulkUploadStatusHistory>();
        }
    
        public int BulkUploadStatusId { get; set; }
        public string BulkUploadStatusName { get; set; }
        public string BulkUploadStatusText { get; set; }
    
        public virtual ICollection<BulkUploadStatusHistory> BulkUploadStatusHistories { get; set; }
    }
}
