//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkUploadStatusHistory
    {
        public int BulkUploadStatusHistoryId { get; set; }
        public int BulkUploadId { get; set; }
        public int BulkUploadStatusId { get; set; }
        public string LoggedInUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BulkUpload BulkUpload { get; set; }
        public virtual BulkUploadStatu BulkUploadStatu { get; set; }
    }
}
