//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkUploadProvider
    {
        public int BulkUploadProviderId { get; set; }
        public int BulkUploadId { get; set; }
        public int ProviderId { get; set; }
        public Nullable<bool> IsAuthorisedUpload { get; set; }
    
        public virtual BulkUpload BulkUpload { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
