//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkUpload
    {
        public BulkUpload()
        {
            this.BulkUploadStatusHistories = new HashSet<BulkUploadStatusHistory>();
            this.BulkUploadProviders = new HashSet<BulkUploadProvider>();
            this.BulkUploadExceptionItems = new HashSet<BulkUploadExceptionItem>();
        }
    
        public int BulkUploadId { get; set; }
        public Nullable<int> UserProviderId { get; set; }
        public Nullable<int> UserOrganisationId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> ExistingCourses { get; set; }
        public Nullable<int> NewCourses { get; set; }
        public Nullable<int> InvalidCourses { get; set; }
        public Nullable<int> ExistingVenues { get; set; }
        public Nullable<int> NewVenues { get; set; }
        public Nullable<int> InvalidVenues { get; set; }
        public Nullable<int> ExistingOpportunities { get; set; }
        public Nullable<int> NewOpportunities { get; set; }
        public Nullable<int> InvalidOpportunities { get; set; }
        public Nullable<System.Guid> ProcessingToken { get; set; }
        public int FileSize { get; set; }
        public Nullable<int> ExistingApprenticeships { get; set; }
        public Nullable<int> NewApprenticeships { get; set; }
        public Nullable<int> InvalidApprenticeships { get; set; }
        public Nullable<int> ExistingLocations { get; set; }
        public Nullable<int> NewLocations { get; set; }
        public Nullable<int> InvalidLocations { get; set; }
        public Nullable<int> ExistingDeliveryLocations { get; set; }
        public Nullable<int> NewDeliveryLocations { get; set; }
        public Nullable<int> InvalidDeliveryLocations { get; set; }
        public Nullable<int> FileContentType { get; set; }
    
        public virtual ICollection<BulkUploadStatusHistory> BulkUploadStatusHistories { get; set; }
        public virtual ICollection<BulkUploadProvider> BulkUploadProviders { get; set; }
        public virtual ICollection<BulkUploadExceptionItem> BulkUploadExceptionItems { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
