//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkUploadErrorType
    {
        public BulkUploadErrorType()
        {
            this.BulkUploadExceptionItems = new HashSet<BulkUploadExceptionItem>();
        }
    
        public int BulkUploadErrorTypeId { get; set; }
        public string BulkUploadErrorTypeName { get; set; }
    
        public virtual ICollection<BulkUploadExceptionItem> BulkUploadExceptionItems { get; set; }
    }
}
