//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ContentId { get; set; }
        public int Version { get; set; }
        public string Path { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Scripts { get; set; }
        public string Styles { get; set; }
        public string Summary { get; set; }
        public int UserContext { get; set; }
        public bool Embed { get; set; }
        public int RecordStatusId { get; set; }
        public int LanguageId { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Language Language { get; set; }
        public virtual RecordStatu RecordStatu { get; set; }
    }
}
