//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseLearnDirectClassification
    {
        public int CourseId { get; set; }
        public string LearnDirectClassificationRef { get; set; }
        public int ClassificationOrder { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual LearnDirectClassification LearnDirectClassification { get; set; }
    }
}
