//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInstanceStartDate
    {
        public int CourseInstanceStartDateId { get; set; }
        public int CourseInstanceId { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool IsMonthOnlyStartDate { get; set; }
        public Nullable<int> PlacesAvailable { get; set; }
    
        public virtual CourseInstance CourseInstance { get; set; }
    }
}
