//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseLearnDirectClassifications = new HashSet<CourseLearnDirectClassification>();
            this.CourseInstances = new HashSet<CourseInstance>();
        }
    
        public int CourseId { get; set; }
        public int ProviderId { get; set; }
        public string CourseTitle { get; set; }
        public string CourseSummary { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
        public int AddedByApplicationId { get; set; }
        public int RecordStatusId { get; set; }
        public string LearningAimRefId { get; set; }
        public Nullable<int> QualificationLevelId { get; set; }
        public string EntryRequirements { get; set; }
        public string ProviderOwnCourseRef { get; set; }
        public string Url { get; set; }
        public string BookingUrl { get; set; }
        public string AssessmentMethod { get; set; }
        public string EquipmentRequired { get; set; }
        public Nullable<int> WhenNoLarQualificationTypeId { get; set; }
        public string WhenNoLarQualificationTitle { get; set; }
        public string AwardingOrganisationName { get; set; }
        public Nullable<int> UcasTariffPoints { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual LearningAim LearningAim { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual QualificationLevel QualificationLevel { get; set; }
        public virtual QualificationType QualificationType { get; set; }
        public virtual RecordStatu RecordStatu { get; set; }
        public virtual ICollection<CourseLearnDirectClassification> CourseLearnDirectClassifications { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
    }
}
