//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DfEEstablishmentStatu
    {
        public int DfEEstablishmentStatusId { get; set; }
        public string DfEEstablishmentStatusCode { get; set; }
        public string DfEEstablishmentStatusName { get; set; }
        public Nullable<int> DfEProviderStatusId { get; set; }
    
        public virtual DfEProviderStatu DfEProviderStatu { get; set; }
    }
}
