//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DfEProviderStatu
    {
        public DfEProviderStatu()
        {
            this.DfEEstablishmentStatus = new HashSet<DfEEstablishmentStatu>();
            this.Providers = new HashSet<Provider>();
        }
    
        public int DfEProviderStatusId { get; set; }
        public string DfEProviderStatusCode { get; set; }
        public string DfEProviderStatusName { get; set; }
        public int DfEWsProviderStatusId { get; set; }
    
        public virtual ICollection<DfEEstablishmentStatu> DfEEstablishmentStatus { get; set; }
        public virtual DfEWsProviderStatu DfEWsProviderStatu { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
    }
}
