//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DurationUnit
    {
        public DurationUnit()
        {
            this.CourseInstances = new HashSet<CourseInstance>();
        }
    
        public int DurationUnitId { get; set; }
        public string DurationUnitName { get; set; }
        public string BulkUploadRef { get; set; }
        public int DisplayOrder { get; set; }
        public double WeekEquivalent { get; set; }
    
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
    }
}
