//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoLocation
    {
        public string Postcode { get; set; }
        public double Lat { get; set; }
        public double Lng { get; set; }
        public double Northing { get; set; }
        public double Easting { get; set; }
    }
}
