//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalEventUser
    {
        public GlobalEventUser()
        {
            this.GlobalEventLogs = new HashSet<GlobalEventLog>();
        }
    
        public int UserID { get; set; }
        public string User { get; set; }
    
        public virtual ICollection<GlobalEventLog> GlobalEventLogs { get; set; }
    }
}
