//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportBatchProvider
    {
        public int ImportBatchId { get; set; }
        public int ProviderId { get; set; }
        public bool HasProviderLevelData { get; set; }
        public bool HasApprenticeshipLevelData { get; set; }
        public bool ExistingProvider { get; set; }
        public System.DateTime ImportDateTimeUtc { get; set; }
        public string ManuallyAddedByUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ImportBatch ImportBatch { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
