//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageKeyGroup
    {
        public LanguageKeyGroup()
        {
            this.LanguageKeyChilds = new HashSet<LanguageKeyChild>();
        }
    
        public int LanguageKeyGroupId { get; set; }
        public string KeyGroupName { get; set; }
    
        public virtual ICollection<LanguageKeyChild> LanguageKeyChilds { get; set; }
    }
}
