//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageKeyChild
    {
        public LanguageKeyChild()
        {
            this.LanguageFields = new HashSet<LanguageField>();
        }
    
        public int LanguageKeyChildId { get; set; }
        public int LanguageKeyGroupId { get; set; }
        public string KeyChildName { get; set; }
    
        public virtual ICollection<LanguageField> LanguageFields { get; set; }
        public virtual LanguageKeyGroup LanguageKeyGroup { get; set; }
    }
}
