//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearnDirectClassification
    {
        public LearnDirectClassification()
        {
            this.CourseLearnDirectClassifications = new HashSet<CourseLearnDirectClassification>();
            this.LearningAims = new HashSet<LearningAim>();
            this.LearningAims1 = new HashSet<LearningAim>();
            this.LearningAims2 = new HashSet<LearningAim>();
        }
    
        public string LearnDirectClassificationRef { get; set; }
        public string LearnDirectClassSystemCodeDesc { get; set; }
    
        public virtual ICollection<CourseLearnDirectClassification> CourseLearnDirectClassifications { get; set; }
        public virtual ICollection<LearningAim> LearningAims { get; set; }
        public virtual ICollection<LearningAim> LearningAims1 { get; set; }
        public virtual ICollection<LearningAim> LearningAims2 { get; set; }
    }
}
