//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningAim
    {
        public LearningAim()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public string LearningAimRefId { get; set; }
        public string Qualification { get; set; }
        public string LearningAimTitle { get; set; }
        public string LearningAimAwardOrgCode { get; set; }
        public Nullable<int> QualificationTypeId { get; set; }
        public bool IndependentLivingSkills { get; set; }
        public string ErAppStatus { get; set; }
        public string SkillsForLife { get; set; }
        public string LearnDirectClassSystemCode1 { get; set; }
        public string LearnDirectClassSystemCode2 { get; set; }
        public string LearnDirectClassSystemCode3 { get; set; }
        public int RecordStatusId { get; set; }
        public Nullable<int> QualificationLevelId { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual LearningAimAwardOrg LearningAimAwardOrg { get; set; }
        public virtual QualificationType QualificationType { get; set; }
        public virtual LearnDirectClassification LearnDirectClassification1 { get; set; }
        public virtual LearnDirectClassification LearnDirectClassification2 { get; set; }
        public virtual LearnDirectClassification LearnDirectClassification3 { get; set; }
        public virtual RecordStatu RecordStatu { get; set; }
    }
}
