//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningAimAwardOrg
    {
        public LearningAimAwardOrg()
        {
            this.LearningAims = new HashSet<LearningAim>();
        }
    
        public string LearningAimAwardOrgCode { get; set; }
        public string AwardOrgName { get; set; }
    
        public virtual ICollection<LearningAim> LearningAims { get; set; }
    }
}
