//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetadataUpload
    {
        public int MetadataUploadId { get; set; }
        public int MetadataUploadTypeId { get; set; }
        public int RowsBefore { get; set; }
        public int RowsAfter { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public int DurationInMilliseconds { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSizeInBytes { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MetadataUploadType MetadataUploadType { get; set; }
    }
}
