//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetadataUploadType
    {
        public MetadataUploadType()
        {
            this.MetadataUploads = new HashSet<MetadataUpload>();
        }
    
        public int MetadataUploadTypeId { get; set; }
        public string MetadataUploadTypeName { get; set; }
        public string MetadataUploadTypeDescription { get; set; }
    
        public virtual ICollection<MetadataUpload> MetadataUploads { get; set; }
    }
}
