//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public Organisation()
        {
            this.OrganisationProviders = new HashSet<OrganisationProvider>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.CourseInstances = new HashSet<CourseInstance>();
            this.CourseInstances1 = new HashSet<CourseInstance>();
            this.UserProvisionHistories = new HashSet<UserProvisionHistory>();
            this.BulkUploads = new HashSet<BulkUpload>();
        }
    
        public int OrganisationId { get; set; }
        public Nullable<int> UKPRN { get; set; }
        public string OrganisationName { get; set; }
        public string OrganisationAlias { get; set; }
        public Nullable<int> UPIN { get; set; }
        public int OrganisationTypeId { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public bool IsContractingBody { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
        public int RecordStatusId { get; set; }
        public string RelationshipManagerUserId { get; set; }
        public string InformationOfficerUserId { get; set; }
        public int AddressId { get; set; }
        public bool Loans24Plus { get; set; }
        public bool QualityEmailsPaused { get; set; }
        public Nullable<int> QualityEmailStatusId { get; set; }
        public bool BulkUploadPending { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual OrganisationType OrganisationType { get; set; }
        public virtual RecordStatu RecordStatu { get; set; }
        public virtual ICollection<OrganisationProvider> OrganisationProviders { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances1 { get; set; }
        public virtual QualityEmailStatuses QualityEmailStatus { get; set; }
        public virtual OrganisationQualityScore OrganisationQualityScore { get; set; }
        public virtual ICollection<UserProvisionHistory> UserProvisionHistories { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser21 { get; set; }
        public virtual ICollection<BulkUpload> BulkUploads { get; set; }
        public virtual Ukrlp Ukrlp { get; set; }
    }
}
