//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganisationProvider
    {
        public int OrganisationId { get; set; }
        public int ProviderId { get; set; }
        public bool IsRejected { get; set; }
        public bool IsAccepted { get; set; }
        public string RespondedByUserId { get; set; }
        public Nullable<System.DateTime> RespondedByDateTimeUtc { get; set; }
        public bool CanOrganisationEditProvider { get; set; }
        public string Reason { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
