//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderTASRefresh
    {
        public int TASRefreshId { get; set; }
        public Nullable<int> ImportBatchId { get; set; }
        public int ProviderId { get; set; }
        public System.DateTime RefreshTimeUtc { get; set; }
        public string RefreshUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ImportBatch ImportBatch { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
