//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderUserType
    {
        public ProviderUserType()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.ProviderUserTypeInRoles = new HashSet<ProviderUserTypeInRole>();
        }
    
        public int ProviderUserTypeId { get; set; }
        public string ProviderUserTypeName { get; set; }
        public bool IsRelationshipManager { get; set; }
        public bool IsInformationOfficer { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<ProviderUserTypeInRole> ProviderUserTypeInRoles { get; set; }
    }
}
