//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderPortalUsageStatistic
    {
        public int ProviderId { get; set; }
        public System.DateTime DayDate { get; set; }
        public int StatisticTypeId { get; set; }
        public int StatisticActionId { get; set; }
        public int Count { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual StatisticAction StatisticAction { get; set; }
        public virtual StatisticType StatisticType { get; set; }
    }
}
