//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Courses = new HashSet<Course>();
            this.ProviderPortalUsageStatistics = new HashSet<ProviderPortalUsageStatistic>();
            this.Venues = new HashSet<Venue>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.OrganisationProviders = new HashSet<OrganisationProvider>();
            this.CourseInstances = new HashSet<CourseInstance>();
            this.CourseInstances1 = new HashSet<CourseInstance>();
            this.BulkUploadProviders = new HashSet<BulkUploadProvider>();
            this.QualityEmailLogs = new HashSet<QualityEmailLog>();
            this.UserProvisionHistories = new HashSet<UserProvisionHistory>();
            this.Apprenticeships = new HashSet<Apprenticeship>();
            this.Locations = new HashSet<Location>();
            this.BulkUploads = new HashSet<BulkUpload>();
            this.BulkUploadExceptionItems = new HashSet<BulkUploadExceptionItem>();
            this.ProviderQACompliances = new HashSet<ProviderQACompliance>();
            this.ProviderQAStyles = new HashSet<ProviderQAStyle>();
            this.AllCoursesOKConfirmations = new HashSet<Provider_AllCoursesOKConfirmations>();
            this.ProviderUnableToCompletes = new HashSet<ProviderUnableToComplete>();
            this.ImportBatches = new HashSet<ImportBatchProvider>();
            this.ProviderTASRefreshes = new HashSet<ProviderTASRefresh>();
        }
    
        public int ProviderId { get; set; }
        public string ProviderName { get; set; }
        public string ProviderNameAlias { get; set; }
        public bool Loans24Plus { get; set; }
        public int Ukprn { get; set; }
        public int ProviderTypeId { get; set; }
        public int RecordStatusId { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
        public Nullable<int> ProviderRegionId { get; set; }
        public bool IsContractingBody { get; set; }
        public string ProviderTrackingUrl { get; set; }
        public string VenueTrackingUrl { get; set; }
        public string CourseTrackingUrl { get; set; }
        public string BookingTrackingUrl { get; set; }
        public string RelationshipManagerUserId { get; set; }
        public string InformationOfficerUserId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> UPIN { get; set; }
        public Nullable<decimal> FeChoicesLearner { get; set; }
        public Nullable<decimal> FeChoicesEmployer { get; set; }
        public Nullable<int> FeChoicesDestination { get; set; }
        public Nullable<System.DateTime> FeChoicesUpdatedDateTimeUtc { get; set; }
        public bool QualityEmailsPaused { get; set; }
        public Nullable<int> QualityEmailStatusId { get; set; }
        public Nullable<System.DateTime> TrafficLightEmailDateTimeUtc { get; set; }
        public bool DFE1619Funded { get; set; }
        public bool SFAFunded { get; set; }
        public Nullable<int> DfENumber { get; set; }
        public Nullable<int> DfEUrn { get; set; }
        public Nullable<int> DfEProviderTypeId { get; set; }
        public Nullable<int> DfEProviderStatusId { get; set; }
        public Nullable<int> DfELocalAuthorityId { get; set; }
        public Nullable<int> DfERegionId { get; set; }
        public Nullable<int> DfEEstablishmentTypeId { get; set; }
        public Nullable<int> DfEEstablishmentNumber { get; set; }
        public Nullable<int> StatutoryLowestAge { get; set; }
        public string AgeRange { get; set; }
        public Nullable<int> AnnualSchoolCensusLowestAge { get; set; }
        public Nullable<int> AnnualSchoolCensusHighestAge { get; set; }
        public Nullable<int> CompanyRegistrationNumber { get; set; }
        public Nullable<int> Uid { get; set; }
        public Nullable<int> StatutoryHighestAge { get; set; }
        public Nullable<int> SecureAccessId { get; set; }
        public bool BulkUploadPending { get; set; }
        public bool PublishData { get; set; }
        public string MarketingInformation { get; set; }
        public bool NationalApprenticeshipProvider { get; set; }
        public bool ApprenticeshipContract { get; set; }
        public bool PassedOverallQAChecks { get; set; }
        public bool DataReadyToQA { get; set; }
        public bool RoATPFFlag { get; set; }
        public Nullable<System.DateTime> LastAllDataUpToDateTimeUtc { get; set; }
        public Nullable<int> RoATPProviderTypeId { get; set; }
        public Nullable<System.DateTime> RoATPStartDate { get; set; }
        public Nullable<System.DateTime> MarketingInformationUpdatedDateUtc { get; set; }
        public string TradingName { get; set; }
        public Nullable<bool> IsTASOnly { get; set; }
        public Nullable<int> MaxLocations { get; set; }
        public string MaxLocationsUserId { get; set; }
        public Nullable<System.DateTime> MaxLocationsDateTimeUtc { get; set; }
        public bool TASRefreshOverride { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ProviderRegion ProviderRegion { get; set; }
        public virtual ProviderType ProviderType { get; set; }
        public virtual RecordStatu RecordStatu { get; set; }
        public virtual Ukrlp Ukrlp { get; set; }
        public virtual ICollection<ProviderPortalUsageStatistic> ProviderPortalUsageStatistics { get; set; }
        public virtual ICollection<Venue> Venues { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<OrganisationProvider> OrganisationProviders { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances1 { get; set; }
        public virtual QualityEmailStatuses QualityEmailStatus { get; set; }
        public virtual FEChoice FEChoice { get; set; }
        public virtual DfEEstablishmentType DfEEstablishmentType { get; set; }
        public virtual DfELocalAuthority DfELocalAuthority { get; set; }
        public virtual DfEProviderStatu DfEProviderStatu { get; set; }
        public virtual DfEProviderType DfEProviderType { get; set; }
        public virtual DfERegion DfERegion { get; set; }
        public virtual ICollection<BulkUploadProvider> BulkUploadProviders { get; set; }
        public virtual QualityScore QualityScore { get; set; }
        public virtual ICollection<QualityEmailLog> QualityEmailLogs { get; set; }
        public virtual ICollection<UserProvisionHistory> UserProvisionHistories { get; set; }
        public virtual ICollection<Apprenticeship> Apprenticeships { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser21 { get; set; }
        public virtual ICollection<BulkUpload> BulkUploads { get; set; }
        public virtual ICollection<BulkUploadExceptionItem> BulkUploadExceptionItems { get; set; }
        public virtual ICollection<ProviderQACompliance> ProviderQACompliances { get; set; }
        public virtual ICollection<ProviderQAStyle> ProviderQAStyles { get; set; }
        public virtual ICollection<Provider_AllCoursesOKConfirmations> AllCoursesOKConfirmations { get; set; }
        public virtual RoATPProviderType RoATPProviderType { get; set; }
        public virtual ICollection<ProviderUnableToComplete> ProviderUnableToCompletes { get; set; }
        public virtual ICollection<ImportBatchProvider> ImportBatches { get; set; }
        public virtual AspNetUser MaxLocationsUser { get; set; }
        public virtual ICollection<ProviderTASRefresh> ProviderTASRefreshes { get; set; }
    }
}
