//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderQAStyle
    {
        public ProviderQAStyle()
        {
            this.QAStyleFailureReasons = new HashSet<QAStyleFailureReason>();
        }
    
        public int ProviderQAStyleId { get; set; }
        public int ProviderId { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string TextQAd { get; set; }
        public bool Passed { get; set; }
        public string DetailsOfQA { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ICollection<QAStyleFailureReason> QAStyleFailureReasons { get; set; }
    }
}
