//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicAPIUser
    {
        public System.Guid PublicAPIUserId { get; set; }
        public string CompanyName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string CreatedByUserId { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
        public int RecordStatusId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
    
        public virtual RecordStatu RecordStatu { get; set; }
    }
}
