//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityEmailStatuses
    {
        public QualityEmailStatuses()
        {
            this.Providers = new HashSet<Provider>();
            this.Organisations = new HashSet<Organisation>();
        }
    
        public int QualityEmailStatusId { get; set; }
        public string QualityEmailStatusDesc { get; set; }
    
        public virtual ICollection<Provider> Providers { get; set; }
        public virtual ICollection<Organisation> Organisations { get; set; }
    }
}
