//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityEmailLog
    {
        public int QualityEmailLogId { get; set; }
        public int ProviderId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
        public int TrafficLightStatusId { get; set; }
        public bool SFAFunded { get; set; }
        public bool DFE1619Funded { get; set; }
        public bool QualityEmailsPaused { get; set; }
        public bool HasValidRecipients { get; set; }
        public Nullable<int> EmailTemplateId { get; set; }
        public Nullable<System.DateTime> EmailDateTimeUtc { get; set; }
        public Nullable<int> NextEmailTemplateId { get; set; }
        public Nullable<System.DateTime> NextEmailDateTimeUtc { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUtc { get; set; }
    
        public virtual EmailTemplate EmailTemplate { get; set; }
        public virtual EmailTemplate EmailTemplate1 { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
