//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualificationType
    {
        public QualificationType()
        {
            this.Courses = new HashSet<Course>();
            this.LearningAims = new HashSet<LearningAim>();
        }
    
        public int QualificationTypeId { get; set; }
        public string QualificationTypeName { get; set; }
        public int DisplayOrder { get; set; }
        public string BulkUploadRef { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<LearningAim> LearningAims { get; set; }
    }
}
