//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualificationLevel
    {
        public QualificationLevel()
        {
            this.Courses = new HashSet<Course>();
            this.SearchPhrases = new HashSet<SearchPhrase>();
        }
    
        public int QualificationLevelId { get; set; }
        public string QualificationLevelName { get; set; }
        public string BulkUploadRef { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<SearchPhrase> SearchPhrases { get; set; }
    }
}
