//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityScore
    {
        public int ProviderId { get; set; }
        public int Courses { get; set; }
        public int CourseInstances { get; set; }
        public int EstimatedFundingAllocation { get; set; }
        public int EstimatedFundingAllocationPerCourseInstance { get; set; }
        public int DistinctCourseTitles { get; set; }
        public int DistinctLearningAims { get; set; }
        public int DistinctCourseUrls { get; set; }
        public int CoursesWithBookingUrls { get; set; }
        public int DistinctCourseBookingUrls { get; set; }
        public int CoursesWithSpecificStartDates { get; set; }
        public int CoursesWithSpecificPrices { get; set; }
        public int CoursesWithLongSummary { get; set; }
        public int CoursesWithUrls { get; set; }
        public int CoursesWithDistinctLongSummary { get; set; }
        public decimal CoursesWithFutureStartDates { get; set; }
        public int CoursesWithLearningAims { get; set; }
        public int CoursesWithAnEntryRequirement { get; set; }
        public Nullable<decimal> AutoAggregateQualityRating { get; set; }
        public Nullable<decimal> AutoAuditQualityRating { get; set; }
        public Nullable<int> ManualAuditQualityRating { get; set; }
        public Nullable<int> OverallQualityRating { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
        public Nullable<int> ModifiedByApplicationId { get; set; }
        public string ModifiedByUserId { get; set; }
        public System.DateTime CalculatedDateTimeUtc { get; set; }
        public string AuditedByUserId { get; set; }
        public Nullable<System.DateTime> AuditedDateTimeUtc { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
