//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordStatu
    {
        public RecordStatu()
        {
            this.A10FundingCode = new HashSet<A10FundingCode>();
            this.Courses = new HashSet<Course>();
            this.Providers = new HashSet<Provider>();
            this.Ukrlps = new HashSet<Ukrlp>();
            this.Venues = new HashSet<Venue>();
            this.Organisations = new HashSet<Organisation>();
            this.CourseInstances = new HashSet<CourseInstance>();
            this.PublicAPIUsers = new HashSet<PublicAPIUser>();
            this.Contents = new HashSet<Content>();
            this.Apprenticeships = new HashSet<Apprenticeship>();
            this.DeliveryModes = new HashSet<DeliveryMode>();
            this.Locations = new HashSet<Location>();
            this.Standards = new HashSet<Standard>();
            this.ApprenticeshipLocations = new HashSet<ApprenticeshipLocation>();
            this.Frameworks = new HashSet<Framework>();
            this.LearningAims = new HashSet<LearningAim>();
            this.QAComplianceFailureReasons = new HashSet<QAComplianceFailureReason>();
            this.QAStyleFailureReasons = new HashSet<QAStyleFailureReason>();
            this.UnableToCompleteFailureReasons = new HashSet<UnableToCompleteFailureReason>();
            this.SearchPhrases = new HashSet<SearchPhrase>();
        }
    
        public int RecordStatusId { get; set; }
        public string RecordStatusName { get; set; }
        public bool IsPublished { get; set; }
        public bool IsArchived { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<A10FundingCode> A10FundingCode { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
        public virtual ICollection<Ukrlp> Ukrlps { get; set; }
        public virtual ICollection<Venue> Venues { get; set; }
        public virtual ICollection<Organisation> Organisations { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
        public virtual ICollection<PublicAPIUser> PublicAPIUsers { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<Apprenticeship> Apprenticeships { get; set; }
        public virtual ICollection<DeliveryMode> DeliveryModes { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Standard> Standards { get; set; }
        public virtual ICollection<ApprenticeshipLocation> ApprenticeshipLocations { get; set; }
        public virtual ICollection<Framework> Frameworks { get; set; }
        public virtual ICollection<LearningAim> LearningAims { get; set; }
        public virtual ICollection<QAComplianceFailureReason> QAComplianceFailureReasons { get; set; }
        public virtual ICollection<QAStyleFailureReason> QAStyleFailureReasons { get; set; }
        public virtual ICollection<UnableToCompleteFailureReason> UnableToCompleteFailureReasons { get; set; }
        public virtual ICollection<SearchPhrase> SearchPhrases { get; set; }
    }
}
