//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchPhrase
    {
        public SearchPhrase()
        {
            this.AttendancePatterns = new HashSet<AttendancePattern>();
            this.AttendanceTypes = new HashSet<AttendanceType>();
            this.QualificationLevels = new HashSet<QualificationLevel>();
            this.StudyModes = new HashSet<StudyMode>();
        }
    
        public int SearchPhraseId { get; set; }
        public string Phrase { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
        public int Ordinal { get; set; }
        public int RecordStatusId { get; set; }
        public bool RemovePhraseFromSearch { get; set; }
    
        public virtual ICollection<AttendancePattern> AttendancePatterns { get; set; }
        public virtual ICollection<AttendanceType> AttendanceTypes { get; set; }
        public virtual ICollection<QualificationLevel> QualificationLevels { get; set; }
        public virtual ICollection<StudyMode> StudyModes { get; set; }
        public virtual RecordStatu RecordStatus { get; set; }
        public virtual AspNetUser CreatedByUser { get; set; }
        public virtual AspNetUser ModifiedByUser { get; set; }
    }
}
