//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCAS_PG_Course
    {
        public int CourseId { get; set; }
        public string UniqueId { get; set; }
        public int ProviderId { get; set; }
        public string CourseTitle { get; set; }
        public string CourseSummary { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string CreatedByUserId { get; set; }
    }
}
