//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCAS_PlaceOfStudy
    {
        public int PlaceOfStudyId { get; set; }
        public int OrgId { get; set; }
        public string PlaceOfStudy { get; set; }
        public string PlaceOfStudyDescription { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> TownId { get; set; }
        public string Postcode { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string CreatedByUserId { get; set; }
    }
}
