//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCAS_Course
    {
        public int CourseId { get; set; }
        public int OrgId { get; set; }
        public string CourseTitle { get; set; }
        public string Summary { get; set; }
        public string Modules { get; set; }
        public string AssessmentMethods { get; set; }
        public string AdditionalEntry { get; set; }
        public string NoOfPlaces { get; set; }
        public string HESA1 { get; set; }
        public string HESA2 { get; set; }
        public string HESA3 { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string CreatedByUserId { get; set; }
    }
}
