//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCAS_PG_CourseOption
    {
        public int CourseOptionId { get; set; }
        public string UniqueId { get; set; }
        public int CourseId { get; set; }
        public int LocationId { get; set; }
        public string Qualification { get; set; }
        public string QualificationLevel { get; set; }
        public string EntryRequirements { get; set; }
        public string AssessmentMethods { get; set; }
        public string StudyMode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public int DurationValue { get; set; }
        public string DurationType { get; set; }
    }
}
