//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCAS_StartsIndex
    {
        public int StartIndexId { get; set; }
        public int StartId { get; set; }
        public Nullable<int> CourseIndexId { get; set; }
        public Nullable<int> PlaceOfStudyId { get; set; }
    }
}
