//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCAS_CoursesIndex
    {
        public int CourseIndexId { get; set; }
        public int CourseId { get; set; }
        public Nullable<double> MinDuration { get; set; }
        public Nullable<double> MaxDuration { get; set; }
        public Nullable<int> DurationId { get; set; }
        public int QualificationId { get; set; }
        public Nullable<int> StudyModeId { get; set; }
    }
}
