//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCAS_CourseEntry
    {
        public int CourseEntryId { get; set; }
        public int CourseId { get; set; }
        public int EntryId { get; set; }
        public string MinPoints { get; set; }
        public string MaxPoints { get; set; }
        public string Subjects { get; set; }
    }
}
