//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCAS_PG_CourseOptionFee
    {
        public int CourseOptionFeeId { get; set; }
        public int CourseOptionId { get; set; }
        public double Fee { get; set; }
        public string Currency { get; set; }
        public string FeeDurationPeriod { get; set; }
        public string Locale { get; set; }
    }
}
