//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ukrlp
    {
        public Ukrlp()
        {
            this.Providers = new HashSet<Provider>();
            this.Organisations = new HashSet<Organisation>();
        }
    
        public int Ukprn { get; set; }
        public string LegalName { get; set; }
        public string TradingName { get; set; }
        public string LegalPhoneNumber { get; set; }
        public string LegalFaxNumber { get; set; }
        public string PrimaryUKPhone { get; set; }
        public string PrimaryUKFax { get; set; }
        public string PrimaryContactName { get; set; }
        public string CompanyRegistration { get; set; }
        public string CharityRegistration { get; set; }
        public string TaxReferenceNumber { get; set; }
        public Nullable<int> UkrlpStatus { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUtc { get; set; }
        public Nullable<int> LegalAddressId { get; set; }
        public Nullable<int> PrimaryAddressId { get; set; }
    
        public virtual Address LegalAddress { get; set; }
        public virtual Address PrimaryAddress { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
        public virtual RecordStatu RecordStatu { get; set; }
        public virtual ICollection<Organisation> Organisations { get; set; }
    }
}
