//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProvisionHistory
    {
        public int UserProvisionHistoryId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
