//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_BulkUploadCurrentStatus
    {
        public int BulkUploadId { get; set; }
        public Nullable<System.Guid> ProcessingToken { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public int FileSize { get; set; }
        public Nullable<int> UserProviderId { get; set; }
        public Nullable<int> UserOrganisationId { get; set; }
        public int BulkUploadStatusHistoryId { get; set; }
        public int BulkUploadStatusId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string LoggedInUserId { get; set; }
        public Nullable<int> NumberOfExceptions { get; set; }
        public Nullable<int> NumberOfProviders { get; set; }
    }
}
