//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.CourseInstances = new HashSet<CourseInstance>();
        }
    
        public int VenueId { get; set; }
        public int ProviderId { get; set; }
        public string ProviderOwnVenueRef { get; set; }
        public string VenueName { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Fax { get; set; }
        public string Facilities { get; set; }
        public int RecordStatusId { get; set; }
        public string CreatedByUserId { get; set; }
        public System.DateTime CreatedDateTimeUtc { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeUtc { get; set; }
        public int AddressId { get; set; }
        public string Telephone { get; set; }
        public string BulkUploadVenueId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual RecordStatu RecordStatu { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
