//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueLocation
    {
        public VenueLocation()
        {
            this.VenueLocation1 = new HashSet<VenueLocation>();
            this.CourseInstances = new HashSet<CourseInstance>();
        }
    
        public int VenueLocationId { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> ParentVenueLocationId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geography { get; set; }
        public string Region { get; set; }
        public Nullable<int> Easting { get; set; }
        public Nullable<int> Northing { get; set; }
        public Nullable<int> EastingMin { get; set; }
        public string EastingMax { get; set; }
        public Nullable<int> NorthingMin { get; set; }
        public string NorthingMax { get; set; }
        public string NearestPostcode { get; set; }
    
        public virtual ICollection<VenueLocation> VenueLocation1 { get; set; }
        public virtual VenueLocation ParentVenueLocation { get; set; }
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
    }
}
