//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tribal.SkillsFundingAgency.ProviderPortal.DataWarehouse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWH_Period_Latest
    {
        public string Period { get; set; }
        public string PeriodType { get; set; }
        public string PeriodName { get; set; }
        public System.DateTime PeriodStartDate { get; set; }
        public string PreviousPeriod { get; set; }
        public string NextPeriod { get; set; }
        public System.DateTime NextPeriodStartDate { get; set; }
    }
}
