CREATE PROCEDURE [search].[PublishProvider]
--WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER 
AS BEGIN /* WITH (
      TRANSACTION ISOLATION LEVEL = SNAPSHOT,
      LANGUAGE = 'English') */

DELETE FROM [dbo].[Provider]
INSERT INTO [dbo].[Provider] (
	[ProviderId]
	,  [ProviderName]
	,  [Ukprn]
	,  [ProviderTypeId]
	,  [Email]
	,  [Website]
	,  [Telephone]
	,  [Fax]
	,  [TradingName]
	,  [LegalName]
	,  [UPIN]
	,  [ProviderNameAlias]
	,  [CreatedDateTimeUtc]
	,  [ModifiedDateTimeUtc]
	,  [Loans24Plus]
	,  [RecordStatusId]
	,  [CreatedByUserId]
	,  [ModifiedByUserId]
	,  [AddressLine1]
	,  [AddressLine2]
	,  [Town]
	,  [County]
	,  [Postcode]
	,  [ApplicationId]
	,  [DFE1619Funded]
	,  [SFAFunded]
	,  [FEChoices_LearnerDestination]
	,  [FEChoices_LearnerSatisfaction]
	,  [FEChoices_EmployerSatisfaction]
)
SELECT
	[ProviderId]
	,  [ProviderName]
	,  [Ukprn]
	,  [ProviderTypeId]
	,  [Email]
	,  [Website]
	,  [Telephone]
	,  [Fax]
	,  [TradingName]
	,  [LegalName]
	,  [UPIN]
	,  [ProviderNameAlias]
	,  [CreatedDateTimeUtc]
	,  [ModifiedDateTimeUtc]
	,  [Loans24Plus]
	,  [RecordStatusId]
	,  [CreatedByUserId]
	,  [ModifiedByUserId]
	,  [AddressLine1]
	,  [AddressLine2]
	,  [Town]
	,  [County]
	,  [Postcode]
	,  [ApplicationId]
	,  [DFE1619Funded]
	,  [SFAFunded]
	,  [FEChoices_LearnerDestination]
	,  [FEChoices_LearnerSatisfaction]
	,  [FEChoices_EmployerSatisfaction]
FROM [search].[Provider]
	  
RETURN 0
END