CREATE PROCEDURE [search].[PublishCourseText]
--WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER 
AS BEGIN /* WITH (
      TRANSACTION ISOLATION LEVEL = SNAPSHOT,
      LANGUAGE = 'English') */

DELETE FROM [dbo].[CourseText]
INSERT INTO [dbo].[CourseText] (
	[CourseTextId]
	, [CourseId]
	, [CourseInstanceId]
	, [StudyModeBulkUploadRef]
	, [AttendanceModeBulkUploadRef]
	, [AttendancePatternBulkUploadRef]
	, [QualificationTypeRef]
	, [EastingMin]
	, [EastingMax]
	, [NorthingMin]
	, [NorthingMax]
	, [Easting]
	, [Northing]
	, [SearchText]
	, [NumberOfCourseInstances]
	, [ModifiedDateTimeUtc]
	, [ProviderId]
	, [LdcsCodes]
	, [ProviderName]
	, [ApplyUntilDate]
	, [ApplicationFundingStatus]
	, [CanApplyAllYear]
	, [SearchRegion]
	, [SearchTown]
	, [Postcode]
)
SELECT
	[CourseTextId]
	, [CourseId]
	, [CourseInstanceId]
	, [StudyModeBulkUploadRef]
	, [AttendanceModeBulkUploadRef]
	, [AttendancePatternBulkUploadRef]
	, [QualificationTypeRef]
	, [EastingMin]
	, [EastingMax]
	, [NorthingMin]
	, [NorthingMax]
	, [Easting]
	, [Northing]
	, [SearchText]
	, [NumberOfCourseInstances]
	, [ModifiedDateTimeUtc]
	, [ProviderId]
	, [LdcsCodes]
	, [ProviderName]
	, [ApplyUntilDate]
	, [ApplicationFundingStatus]
	, [CanApplyAllYear]
	, [SearchRegion]
	, [SearchTown]
	, [Postcode]
FROM [search].[CourseText]
	  
RETURN 0
END