<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:type="http://schemas.imservices.gov.uk/alse/coursesearch/type/1.0" xmlns:tns="http://schemas.imservices.gov.uk/alse/coursesearch/service/1.0" targetNamespace="http://schemas.imservices.gov.uk/alse/coursesearch/service/1.0">
	<wsdl:import namespace="http://schemas.imservices.gov.uk/alse/coursesearch/type/1.0" location="type.wsdl"/>
	<wsdl:binding name="ServiceSOAPBinding" type="type:ServiceInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GetCategories">
			<soap:operation soapAction="urn:CourseBrowse"/>
			<wsdl:input name="SubjectBrowseInput">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="SubjectBrowseOutput">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="CategoryFault">
				<soap:fault name="CategoryFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="ProviderSearch">
			<soap:operation soapAction="urn:ProviderSearchOperation"/>
			<wsdl:input name="ProviderSearchInput">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="ProviderSearchOutput">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="ProviderSearchFault">
				<soap:fault name="ProviderSearchFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="CourseList">
			<soap:operation soapAction="urn:CourseListOperation"/>
			<wsdl:input name="CourseListInput">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="CourseListOutput">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="CourseListFault">
				<soap:fault name="CourseListFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="CourseDetail">
			<soap:operation soapAction="urn:CourseDetailOperation"/>
			<wsdl:input name="CourseDetailInput">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="CourseDetailOutput">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="CourseDetailFault">
				<soap:fault name="CourseDetailFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="ProviderDetails">
			<soap:operation soapAction="urn:ProviderDetailsOperation"/>
			<wsdl:input name="ProviderDetailsInput">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="ProviderDetailsOutput">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="ProviderDetailsFault">
				<soap:fault name="ProviderDetailsFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Service">
		<wsdl:port name="ServiceEndpoint" binding="tns:ServiceSOAPBinding">
			<soap:address location="http://www.coursedirectoryproviderportal.org.uk/Search/ServiceV1"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
